// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// internal_frobenius
double internal_frobenius(const arma::mat& x, const arma::mat& y);
RcppExport SEXP _nevada_internal_frobenius(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(internal_frobenius(x, y));
    return rcpp_result_gen;
END_RCPP
}
// internal_spectral
double internal_spectral(const arma::mat& x, const arma::mat& y);
RcppExport SEXP _nevada_internal_spectral(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(internal_spectral(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nevada_internal_frobenius", (DL_FUNC) &_nevada_internal_frobenius, 2},
    {"_nevada_internal_spectral", (DL_FUNC) &_nevada_internal_spectral, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nevada(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
