// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// internal_hamming
double internal_hamming(const arma::mat& x, const arma::mat& y);
RcppExport SEXP _nevada_internal_hamming(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(internal_hamming(x, y));
    return rcpp_result_gen;
END_RCPP
}
// internal_frobenius
double internal_frobenius(const arma::mat& x, const arma::mat& y);
RcppExport SEXP _nevada_internal_frobenius(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(internal_frobenius(x, y));
    return rcpp_result_gen;
END_RCPP
}
// internal_spectral
double internal_spectral(const arma::mat& x, const arma::mat& y);
RcppExport SEXP _nevada_internal_spectral(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(internal_spectral(x, y));
    return rcpp_result_gen;
END_RCPP
}
// internal_root_euclidean
double internal_root_euclidean(const arma::mat& x, const arma::mat& y);
RcppExport SEXP _nevada_internal_root_euclidean(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(internal_root_euclidean(x, y));
    return rcpp_result_gen;
END_RCPP
}
// internal_distance_matrix
arma::mat internal_distance_matrix(const Rcpp::List& z, const std::string& distance);
RcppExport SEXP _nevada_internal_distance_matrix(SEXP zSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(internal_distance_matrix(z, distance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nevada_internal_hamming", (DL_FUNC) &_nevada_internal_hamming, 2},
    {"_nevada_internal_frobenius", (DL_FUNC) &_nevada_internal_frobenius, 2},
    {"_nevada_internal_spectral", (DL_FUNC) &_nevada_internal_spectral, 2},
    {"_nevada_internal_root_euclidean", (DL_FUNC) &_nevada_internal_root_euclidean, 2},
    {"_nevada_internal_distance_matrix", (DL_FUNC) &_nevada_internal_distance_matrix, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nevada(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
