# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_hamming <- function(x, y) {
    .Call('_nevada_internal_hamming', PACKAGE = 'nevada', x, y)
}

internal_frobenius <- function(x, y) {
    .Call('_nevada_internal_frobenius', PACKAGE = 'nevada', x, y)
}

internal_spectral <- function(x, y) {
    .Call('_nevada_internal_spectral', PACKAGE = 'nevada', x, y)
}

internal_root_euclidean <- function(x, y) {
    .Call('_nevada_internal_root_euclidean', PACKAGE = 'nevada', x, y)
}

